### ISSUE TITLE
对于准确度的疑问

### ISSUE THREAD

**Issue by huangsong** [wandergis/coordtransform#1]
转换算法的正确度能有多高？

**Comment by wandergis** [comment]
大约十米，能应付日常需要

**Comment by CntChen** [comment]
**提供一个准确度示例**，没有做完整测试。
对一个`bd09`坐标转换为`cj02`坐标，将该库的转换结果与[高德官方在线转换接口]结果对比。
原始坐标：`bd09` *[112.9778, 22.915835]*
该库转换结果：`cj02` *[112.97124822538616, 22.91014137111559]*
高德官方转换结果：`cj02` *[112.97124803, 22.91014091]*

结论：**经纬度小数点后第7位开始不同，确实是米级别的误差。**

[高德官方在线转换接口]:http://lbsbbs.amap.com/forum.php?mod=viewthread&tid=724&highlight=%E5%9D%90%E6%A0%87%E8%BD%AC%E6%8D%A2

**Comment by wandergis** [comment]
@CntChen 非常感谢您的测试。一般手机定位误差也在这个范围内，还是可以接受的。

**Comment by Luooooooo** [comment]
请问，本库使用的转换参数是怎么计算得到的

**Comment by llli0v0** [comment]
不该问的别问哈哈哈哈哈
