### ISSUE TITLE
火星坐标还是有偏移，而且越往南方，偏移的距离就越远，请问该怎么解决

### ISSUE THREAD

**Issue by 651778286** [wandergis/coordtransform#10]

**Comment by 651778286** [comment]
在补充一点，我使用google地图、OSM地图、高德地图都是这样的结果

**Comment by wandergis** [comment]
目前暂未发现这种情况，不知道你是怎么使用的，最好先确认下原始坐标系和底图的坐标系

**Comment by 651778286** [comment]
@wandergis 非常感谢你的回复，是我拿到的原始数据有问题，才导致的后续一系列错误的结论，我现在使用准确的数据进行测量之后，GCJ02坐标与高德、必应、谷歌等地图都匹配上了，准确度挺高的，现在唯独百度地图和BD09坐标没有匹配上，还在找原因，如有新进展再向您请教，谢谢

**Comment by beikehanbao23** [comment]
@wandergis很不错，没实际用过 不知道精度如何呢？

**Comment by 651778286** [comment]
@wandergis 拿百度地图试来试去，还是没有调整好偏移的问题。
我采集了北京、呼和浩特、武汉、昆明四地的位置信息进行测试，普遍都是往北边偏，而且偏出去很远，我以北京的位置作为参考添加一个偏移量后，呼和浩特往北偏移了大概几十米，武汉往南偏出去几公里，而昆明则往南偏出去十几甚至几十公里了，不知道问题出在哪里了

**Comment by wandergis** [comment]
百度地图的坐标是bd09，不知道你底图是什么坐标系，你应该是转换的关系不对

**Comment by 651778286** [comment]
@wandergis 我通过百度经纬度转换工具获得的结果跟coordtransform获得BD09坐标结果基本一致，看来确实是图层加载方式的问题，我再找找资料，谢谢你哈
