### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by JSW5297** [wandergis/coordtransform#11]
你好，我当时项目需要转换经纬度，所以在网上找资料，好像就是找到你的，然我因为我需要的是java版本，你也没有，所以我就自己弄了一份，当时也忘记star你了。
若你不希望我这样公开，请联系我，我会立马删除次项目，
或者是可以把此项目提交给你当java版本。

https://github.com/JSW5297/CoordinateTransform

**Comment by wandergis** [comment]
https://github.com/geosmart/coordtransform 既然我开源就代表大家都可以使用，但是我看了你的仓库说明一看便知来源于我的这个项目，但未提及我项目，转载还得标明一下出处是不是

**Comment by JSW5297** [comment]
若你感觉这样会侵犯你的创作的话，我可以去把项目删了～～

**Comment by wandergis** [comment]
建议你把放到显眼的位置，免得大家对你产生误会。

**Comment by dlsyaim** [comment]
哎。。。。。群主没必要这么介意。
