### ISSUE TITLE
关于这个工具的使用范围。

### ISSUE THREAD

**Issue by liujia1** [wandergis/coordtransform#13]
我的应用包含国内国外。那么在调用这个工具的时候，我是否要先判断地理位置，如果是在天朝才使用这个库的工具呢？

**Comment by wandergis** [comment]
目前对于国内区域判断使用了简单的按照boundingbox去判断，为了库的体积没有使用中国区域的范围去判断点在国内还是国外。

**Comment by liujia1** [comment]
if((pos.coords.latitude>=37 && pos.coords.latitude<=47)&& (pos.coords.latitude>=110 && pos.coords.latitude<=123))我用了这个boundingbox，想确认一下，是否和你一致？

**Comment by wandergis** [comment]
```js
function out_of_china(lng, lat) {
        return (lng < 72.004 || lng > 137.8347) || ((lat < 0.8293 || lat > 55.8271) || false);
    };
```
代码是开源的，你可以自己看

**Comment by wandergis** [comment]
网上查询的 纬度3.86~53.55,经度73.66~135.05
