### ISSUE TITLE
坐标顺序

### ISSUE THREAD

**Issue by JianChuanting** [wandergis/coordtransform#15]
Lat first or Lon first...
市面上好多模块都是Lat在前...合作时候需要转换一下..

**Comment by wandergis** [comment]
lat在前应该是leaflet的做法，个人决绝这样其实是很别扭的，mapbox-gl已经改成了[lng,lat],您可以对你的数据做一次map操作即可，并且这也对应了geojson的规范。

**Comment by JianChuanting** [comment]
我也觉得别扭...来问问你的看法...
系统里好多都是lat在前..在考虑统一用那种顺序..

**Comment by wandergis** [comment]
我个人是建议经度在前

**Comment by Artoria2e5** [comment]
> https://gis.stackexchange.com/a/6048
> 
> There is very strong wording about the coordinate order for display (not interchange). It says that navigators have traditionally used latitude longitude order and to change the order could compromise safety. Use sexagesimal, direction symbols rather than +/-, etc.

**Comment by wandergis** [comment]
参考这个 https://macwright.org/lonlat/
