### ISSUE TITLE
支持geojson的转换吗

### ISSUE THREAD

**Issue by yangdachu** [wandergis/coordtransform#33]
支持geojson的转换吗

**Comment by wandergis** [comment]
命令行版本：https://github.com/wandergis/coordtransform-cli 支持命令行和node对geojson数据进行转换

**Comment by yangdachu** [comment]
> 命令行版本：https://github.com/wandergis/coordtransform-cli 支持命令行和node对geojson数据进行转换

使用到项目里的，只是命令行不太行哦

**Comment by wandergis** [comment]
安装的时候不带-g，就不会全局安装了，使用方式如下
```js
const transformGeoJSON = require('coordtransform-cli');
const anygeojson = { type: 'Point', coordinates: [118, 34] };
let result = transformGeoJSON(anygeojson, 'wgs84togcj02');
```

**Comment by yangdachu** [comment]
> 安装的时候不带-g，就不会全局安装了，使用方式如下
> 
> ```js
> const transformGeoJSON = require('coordtransform-cli');
> const anygeojson = { type: 'Point', coordinates: [118, 34] };
> let result = transformGeoJSON(anygeojson, 'wgs84togcj02');
> ```

多谢多谢
