### ISSUE TITLE
Todo中`墨卡托坐标`的实现

### ISSUE THREAD

**Issue by CntChen** [wandergis/coordtransform#4]
墨卡托是一种投影方式，并不直接与坐标系相关。据我了解主要的地图厂商都是使用`Web Mercatord`的投影方式。**在墨卡托投影后，各地图厂商对瓦片坐标的定义有所不同。**

所以墨卡托投影或瓦片坐标转换直接放入该项目不知道是否合适？
我参考了你的类库，额外写了一个高德地图、百度地图、谷歌地图各自经纬度坐标与瓦片坐标相互转换的类库--[tile-lnglat-transform][tile-lnglat-transform]。

[tile-lnglat-transform]:https://github.com/CntChen/tile-lnglat-transform

**Comment by shanyuk** [comment]
请教下百度地图坐标怎么转换为wgs84坐标？

**Comment by wandergis** [comment]
@CntChen 抱歉，最近在换工作有些忙，一直没有关注仓库的issue，我看了下你写的转换库很不错，如果你方便的话可以给我提pr，我给并入仓库并添加上说明和致谢。
