### ISSUE TITLE
bd09togcj02 方法转换出来的坐标，偏差有些大

### ISSUE THREAD

**Issue by Baiang** [wandergis/coordtransform#9]
bd09togcj02 方法转换出来的坐标，偏差有些大

**Comment by wandergis** [comment]
首先你确定你的坐标是百度的坐标系，然后确认你的底图是国测局坐标系，目前没发现你说的这个问题。

**Comment by Baiang** [comment]
误差在50~100米左右

**Comment by wandergis** [comment]
项目已开源很长时间暂时没发现你说的这种情况，所以还是确认下你的数据和底图比较好，单纯说偏差大无法定位你的具体原因。
